# build.yaml
targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: lib/i18n
          input_file_pattern: .i18n.yaml
          output_directory: lib/i18n
          flutter_integration: true
      freezed:
        options: