// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:iyox_wormhole/rust/frb_generated.dart';

class BuildInfo {
  final BigInt buildTime;
  final bool devBuild;
  final String version;

  const BuildInfo({
    required this.buildTime,
    required this.devBuild,
    required this.version,
  });

  @override
  int get hashCode => buildTime.hashCode ^ devBuild.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildInfo &&
          runtimeType == other.runtimeType &&
          buildTime == other.buildTime &&
          devBuild == other.devBuild &&
          version == other.version;
}
