// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:iyox_wormhole/rust/frb_generated.dart';

enum Events {
  /// Passphrase : String
  code,

  /// Total bytes to transfer : i32
  total,

  /// bytes already sent : i32
  sent,

  /// error : Error or ErrorValue
  error,

  /// Connecting to mailbox server
  connecting,

  /// transfer finished : String
  finished,

  /// type of con : Connectiontype
  connectionType,

  /// indicate start of transaction : i32
  startTransfer,

  /// indicates start of zipping process and total amount of files to zip
  zipFilesTotal,

  /// number of already zipped files
  zipFiles,
  ;
}
