default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    upload_to_play_store(track: 'internal',skip_upload_metadata: true,
                                        skip_upload_images: true,
                                        skip_upload_screenshots: true,
                                        aab: "build/app/outputs/bundle/release/app-release.aab")
  end

  lane :upload_meta do
    upload_to_play_store(track: 'internal', skip_upload_apk: true,
                         skip_upload_aab: true,
                         skip_upload_changelogs: true)
  end
end
