# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
        commitnr = number_of_commits
        changelog_from_git_commits

        upload_to_play_store(track: 'internal',skip_upload_metadata: true,
                                            skip_upload_images: true,
                                            skip_upload_screenshots: true,
                                            aab: "build/app/outputs/bundle/release/app-release.aab")
  end

  desc "elevate apk to aplpha track"
  lane :elevate do

     upload_to_play_store(track: 'internal', track_promote_to: 'production',version_code: commitnr,
     skip_upload_apk: true, skip_upload_aab: true, skip_upload_metadata: true, skip_upload_changelogs: true, skip_upload_images: true, skip_upload_screenshots: true)
  end
end

